"""add auth health columns

Revision ID: 3d9de53f2821
Revises: 428badc2d81e
Create Date: 2026-03-20 15:45:43.425214

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d9de53f2821"
down_revision: str | Sequence[str] | None = "428badc2d81e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_accounts",
        sa.Column("token_status", sa.String(length=30), server_default="ok", nullable=False),
    )
    op.add_column("github_accounts", sa.Column("token_error", sa.Text(), nullable=True))
    op.add_column(
        "github_accounts", sa.Column("token_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("tracked_repos", sa.Column("last_sync_error", sa.Text(), nullable=True))
    op.add_column(
        "tracked_repos", sa.Column("last_sync_error_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "tracked_repos",
        sa.Column("last_successful_sync_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_repos", "last_successful_sync_at")
    op.drop_column("tracked_repos", "last_sync_error_at")
    op.drop_column("tracked_repos", "last_sync_error")
    op.drop_column("github_accounts", "token_checked_at")
    op.drop_column("github_accounts", "token_error")
    op.drop_column("github_accounts", "token_status")
    # ### end Alembic commands ###
