"""add closed_at to pull_requests

Revision ID: a1da0e99d628
Revises: 3d9de53f2821
Create Date: 2026-03-20 16:22:28.212147

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1da0e99d628"
down_revision: str | Sequence[str] | None = "3d9de53f2821"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pull_requests", sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pull_requests", "closed_at")
    # ### end Alembic commands ###
